package db

import (
	"database/sql"
	"log"
	"os"
	"testing"

	// lib/pq driver
	// if not using it directly in the code, must add _
	_ "github.com/lib/pq"
)

const (
	dbDriver = "postgres"
	dbSource = "postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable"
)

var testQueries *Queries
var testDB *sql.DB

// TestMain function is the main entry point of
// all unit test inside 1 specific Golang package (package db).
// Use this testmain to conenct DB with testQueries obj

func TestMain(m *testing.M) {
	var err error

	testDB, err = sql.Open(dbDriver, dbSource)
	if err != nil {
		log.Fatal("cannot connect to db:", err)
	}
	// New() function is defined in db.go, auto generated by sqlc
	testQueries = New(testDB)
	// run the test case, report it back to the test runner, so need to use os.Exit()
	os.Exit(m.Run())
}
